spring:
  profiles:
    # 默认激活 dev 环境
    active: dev
jwt:
  # 签发人
  issuer: quanxiaoha
  # 秘钥
  secret: ddedOh0mLf3A+S3enahnHBgwsLXCeVeEE3Xp2YA+Sz9aFV+C+J7Kmh5omJEANg9wHdupnS0trvbecyQHESWgBw==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer

